FROM node:19

WORKDIR /

COPY package*.json .

RUN npm install

COPY . . 

ENV PORT=3333
ENV SECRET_SESSION=YOUR_SECRETSESSION
ENV DB_HOST=db
ENV DB_USER=root
ENV DB_PASS=root
ENV DB_DB=decashop

ENV MERCADOPAGO_ACCESSTOKEN=YOUR_ACCESSTOKEN
ENV MERCADOPAGO_ACCESSTOKEN_TEST=YOUR_DEVELOPMENT_ACESSTOKEN

ENV NOTIFICATION_URL=https://appurl.com

EXPOSE 3333

CMD [ "npm", "start" ]
#